version: "3.9"
 
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dwh
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    networks:
      dwh_network:
        ipv4_address: 10.5.0.5

  dwh-init:
    image: dwh-init
    volumes:
      - ./python:/usr/src/app
      - ./data:/usr/src/data
    command: bash -c "python /usr/src/app/load_dwh.py"
    #depends_on:
    #  postgres:
    #    condition: service_healthy
    #links: 
    #    - postgres
    networks:
      - dwh_network

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - ./cube:/cube/conf
    networks:
      - dwh_network

networks:
  dwh_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1